### ISSUE TITLE
Please update your wiki!

### ISSUE THREAD

**Issue by danielbrunt57** [kpine/zwave-js-server-docker#22]
The Everspring  SA-370 700 Series also uses the ZGM130S chipset!

[SA370 Z-Wave 700 USB DONGLE](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiQ3puL0Oj4AhXPIDQIHRIEDg8QFnoECAgQAQ&url=https%3A%2F%2Fproducts.z-wavealliance.org%2FProductManual%2FFile%3Ffolder%3D%26filename%3Dproduct_documents%2F3997%2FSA370%2520user%2520manual.pdf&usg=AOvVaw3d3As5q_RmWkc_YJVfhlKU)
```
These controllers are known to use the ZGM130S module:
Zooz ZST10 700
```

**Comment by kpine** [comment]
Were you able to successfully complete an upgrade?

**Comment by danielbrunt57** [comment]
No, not yet!  It is still v7.13.6 but it's almost midnight here now!

**Comment by danielbrunt57** [comment]
It it is successful I will update you...

**Comment by danielbrunt57** [comment]
Okay, so I followed the procedure here and flashed it with [ZW_SerialAPI_Controller_7_17_2_406_ZGM130S_REGION_US.gbl](ZW_SerialAPI_Controller_7_17_2_406_ZGM130S_REGION_US.gbl) but things are not well...

![image](https://user-images.githubusercontent.com/49846893/178074023-0465dbb5-530c-40e8-9b42-7d7999124edf.png)

**Comment by kpine** [comment]
Make sure the region and tx power are set correctly.

![image](https://user-images.githubusercontent.com/791794/178074317-dc2a8dbd-c18a-46bb-913e-7ddafedbfa85.png)

**Comment by danielbrunt57** [comment]
![image](https://user-images.githubusercontent.com/49846893/178074553-4753081c-77d3-439b-acef-a3efeea9a84a.png)
Fixing...

**Comment by danielbrunt57** [comment]
I've changed those 2 settings but no effect.  
Also, I stopped the ZWJS add-on, unplugged the dongle and plugged it back in, restarted ZWJS but the settings did not stick...
![image](https://user-images.githubusercontent.com/49846893/178075503-82870653-a817-4a6a-8c01-5172e6ccf18c.png)

**Comment by kpine** [comment]
Did you click the arrow buttons to apply the settings?

**Comment by danielbrunt57** [comment]
Yes, and saw the two successful API calls.  This time, I applied the settings and simply restarted ZWJS without restarting the dongle and the settings are back to 0.2 and Unknown.

**Comment by danielbrunt57** [comment]
So they're not being applied by the dongle even though the API calls were successful.

**Comment by kpine** [comment]
Sounds like you're hitting multiple bugs, in the driver and/or zwavejs2mqtt. The NVM restore seems to have mangled the region and output power, and changing the settings are not working. I think you'll have to report a bug at the zwavejs2mqtt project at this point to get support.

**Comment by danielbrunt57** [comment]
Wait...NVM restore?  That was not mentioned in the FW update procedure...

**Comment by kpine** [comment]
I was assuming you did an NVM backup and restore, that's not the case, everything was set prior to the update?

**Comment by danielbrunt57** [comment]
I did an NVM backup from RaZberry and restored to SA370-2 v7.13.6 and then just upgraded the firmware.  Should I try another NVM restore?

**Comment by kpine** [comment]
So you never actually observed that it was working prior to the firmware upgrade? I would assume the NVM restore was the cause, because others have experienced that exact same problem. I don't think another restore will help. The issue is that the region and power are wrong, and the fix is to correct them.

**Comment by danielbrunt57** [comment]
No, it was working fine on 7.13.6 after I restore the NVM

**Comment by danielbrunt57** [comment]
So, after the restore, all green lights...
![image](https://user-images.githubusercontent.com/49846893/178077043-ae5d7e10-8e3e-4b8a-9baf-b8463b8c443d.png)
The controller though showed 0.2/unknown.  So I updated the settings, restarted ZWJS and the new settings were still there. 
![image](https://user-images.githubusercontent.com/49846893/178077460-0ed80a21-63a2-4a09-b6ec-944dd8494236.png)
I suspect the settings were correct in the controller after the NVM restore but not reflected in the ZWJS control panel and possibly just restarting ZWJS may have corrected that without me re-applying the settings.

In any event, I seem to be off to the races!!

**Comment by kpine** [comment]
Strange, but glad it's working! I'll add this stick to the list. Thanks.
