### ISSUE TITLE
Wiki update/suggestion

### ISSUE THREAD

**Issue by notmayo** [kpine/zwave-js-server-docker#25]
Heyo, fantastic work! I just wanted to try to contribute to the wiki page here: https://github.com/kpine/zwave-js-server-docker/wiki/700-series-Controller-Firmware-Updates-(Linux)#host-update-method

Between steps 2 & 3, these steps should be added or added as one big step:

3. Add the "testing" branch to your apk repo list: vi /etc/apk/repositories
4. Press the insert key to enable edit mode in vi
5. Add a new line after the last line: https://dl-cdn.alpinelinux.org/alpine/edge/testing
6. Now save and exit vi by pressing the Escape key, and type : followed by wq
7. Install minicom by issuing: apk add minicom && apk add lrzsz
8. (former step 3)

**Comment by kpine** [comment]
Why are those necessary?

**Comment by notmayo** [comment]
The script (zfw-update.sh) requires minicom and minicom depends on lrzsz in order to execute.

**Comment by kpine** [comment]
Right. I had instructions earlier, which I removed. It's assumed they're installed, but I can add them back. The instructions are not that complex though. https://github.com/kpine/zwave-js-server-docker/wiki/700-series-Controller-Firmware-Updates-(Linux)/f2db0d2fd474e32732bbb437c46a6746ef4fb082#preparation

**Comment by notmayo** [comment]
Gotcha. I'm on the latest version, but these modules aren't installed for me running as a vm. :)

**Comment by kpine** [comment]
No problem, thanks for the feedback. I had been testing with HAOS, and the script automatically installs it, so I just forgot.

**Comment by kpine** [comment]
https://github.com/kpine/zwave-js-server-docker/wiki/700-series-Controller-Firmware-Updates-(Linux)/_compare/f38e8a9d21d8a139e7018ed729fac35911d4f296...5a0aee7b20589e05b5640ede05e925523330f428
