### ISSUE TITLE
Question for @kpine re Locks not reporting status after autolocking ????

### ISSUE THREAD

**Issue by thorrrr** [kpine/zwave-js-server-docker#27]
I am going crazy as a noob on Z-Wave trying to get my locks to talk to HA.
Do i need to post a question in GitHub i have tried online [here](https://discordapp.com/channels/330944238910963714/332357267364249621/1031887413968117790) 
The post shows images and the main issue
I have spoken to Daniel Lando who pointed me in the direction of @kpine.
Daniel 
"I can see in your z-ui screenshot it means there is some issue on hass integration side or a device configuration issue. Try asking to @kpine he usually know how to fix such things on HA side :) Hope this helps"

Sorry to bother you but my logs look fine just need to know how to get the entities updated correctly.
I have no doubt i am doing something wrong just looking to get some help please

**Comment by kpine** [comment]
Sorry, this is not the place for driver support.

**Comment by thorrrr** [comment]
> Sorry, this is not the place for driver support.

Please could you point me to the right place

**Comment by kpine** [comment]
If you're using zwave-js-ui, go there.

If you're using HA, go to the community forums or discord.

Last place, node-zwave-js project.
