### ISSUE TITLE
Aeotec Z-stick 700: Strange characters displayed in controllers bootloader when upgrading

### ISSUE THREAD

**Issue by ismarslomic** [kpine/zwave-js-server-docker#30]
I got an Aeotec Z-stick 700 (with firmware `v7.17.2`) and tried updating to `v7.18.1` (by using Aeotec [download link](https://aeotec.freshdesk.com/helpdesk/attachments/6161386743) from README). I followed both firmware update instructions, by using Docker container and running bash script from host, but after 10 seconds, when the controllers bootloader is displayed, I get strange characters continously in the command line. It's impossible to quit the process and I never see any menu with options.

Im running Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-56-generic x86_64) on Intel Nuc, and Im ssh into the machine when executing the commands.

**With bash script (but similar with docker container)**
``` (bash)
> sudo bash zfw-update.sh

Welcome to minicom 2.8

OPTIONS: I18n
Port /dev/ttyUSB0

Press CTRL-A Z for help on special keys

Activating the controller's bootloader. It will appear in about 10 seconds...
9...
8...
2!$�.�21"ֵ�21"ֵ�21"ֵ�21"ֵ�s`
1"��s                                                    `
1"��s       `
1"��s       `
1"��s       `
1"���s      `
2�"u`   R��u`
1"گ7�u          `
1"گ7�u      `
1"گ7�u      `
2!$�1�``R�r``
1"���      `
1"���     `
1"���     `
1"���71   `
              ���71
                       ���71
                                ���71
                                         ���s
1"��s                                           `
CTRL-A Z for help | 115200 8N1 | NOR | Minicom 2.8   VT102 | Offline | ttyUSB0
```

**Comment by ismarslomic** [comment]
```
> echo $TERM
xterm-256color
```

**Comment by ismarslomic** [comment]
Replacing `print X` and `sleep X` with `sleep 10` did not have any effect.

**Comment by ismarslomic** [comment]
Found similar issue on [stackoverflow](https://unix.stackexchange.com/questions/292654/garbage-characters-when-using-serial-connection-over-ssh-connection-with-minicom) when using `minicom` through `ssh`. But not sure how to configure `character tx delay`, one of the replies suggests.

**Comment by ismarslomic** [comment]
Hmm, I tried following the upgrade instructions on rpi3 (running raspberrian OS) from the official [Aeotec docs](https://aeotec.freshdesk.com/support/solutions/articles/6000252997-update-z-stick-7-through-raspian-os), but I experienced the same issue with strange/rubbish characters. And that was the case when using _ssh_ and running _locally  from Terminal_ in rpi.

Could it be something with encryption key(s) on my Z-stick?

**Comment by ismarslomic** [comment]
I also managed to set the `character tx delay` to `1` in minicom, as suggested in mentioned stackoverflow thread. But that did not solve the issue.

**Comment by ismarslomic** [comment]
No, I made sure to exit the zwavejs2mqtt docker container, and Home Assistant before starting the upgrade instructions. And now I have moved the Z-stick to my rpi, which is clean installation of raspbian OS, without any service running that uses zwave controller

**Comment by ismarslomic** [comment]
I finally managed to get rid of the rubbish characters and get the bootloader menu readable. Not exactly sure what I did that resolved the issue, but what happened on the last attempt was that I moved the Z-stick back to my Intel Nuc and started `zwavejs2mqtt` container. While the container where running I started the bash script and the issue where gone. I then stopped the `zwavejs2mqtt` container, uploaded the file and run the firmware. Now zwave-js UI shows `v7.18.1`. Closing the issue! Thanks for the hints during the debug session.

**Comment by chrislentz** [comment]
I am experiencing this same issue, but not on SSH. I am trying inside of Ubuntu.

When I launch the docker command, I see the countdown, but when the menu is supposed to pop up, I just get a blank screen with weird characters. I will also note that none of the control commands work. They just produce more strange characters. To exit, I have to close the window and docker stop the running container.

![CleanShot 2022-12-31 at 10 47 09@2x](https://user-images.githubusercontent.com/428312/210149212-58424df8-4257-4177-ae2a-e2dab860c22f.png)

![CleanShot 2022-12-31 at 10 47 36@2x](https://user-images.githubusercontent.com/428312/210149219-877b3eab-8938-463f-962b-ce5e214d7d2e.png)

![CleanShot 2022-12-31 at 10 47 52@2x](https://user-images.githubusercontent.com/428312/210149223-10e254d4-0131-46dd-a59f-65d96e105a7b.png)

**Comment by jutley** [comment]
This seems like an encoding issue. I added these lines to the top of the script and then it worked.

```
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
```

I then removed these lines and it still worked, so clearly there is some state hidden somewhere I am not aware of. Regardless, it worked, and I was able to complete the upgrade. I suggest others running into this issue try this out as well.
