### ISSUE TITLE
Fatal error when running latest version in unprivileged mode on RaspberryPi

### ISSUE THREAD

**Issue by BohdanTkachenko** [kpine/zwave-js-server-docker#5]
Example:
```
$ docker run -it --rm -p 3000:3000 --name=zjs -v "$PWD/cache:/cache" -e NETWORK_KEY="17DFB0C1BED4CABFF54E4B5375E257B3" --device "/dev/ttyUSB1:/dev/zwave" kpine/zwave-js-server:latest

Starting zwave-server: zwave-server --config options.js /dev/zwave


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbee37
```

However, if I run in the privileged mode it works:
```
$ docker run -it --rm -p 3000:3000 --name=zjs -v "$PWD/cache:/cache" -e NETWORK_KEY="17DFB0C1BED4CABFF54E4B5375E257B3" --privileged -e USB_PATH=/dev/ttyUSB1  kpine/zwave-js-server:latest

Starting zwave-server: zwave-server --config options.js /dev/ttyUSB1
18:34:00.356 DRIVER   version 8.0.6
18:34:00.357 DRIVER
18:34:00.358 DRIVER   starting driver...
18:34:00.396 DRIVER   opening serial port /dev/ttyUSB1
18:34:00.425 DRIVER   serial port opened
........
```

I did some digging and it looks like the problem comes from recent docker alpine image 3.13 and above. I don't know if there is a direct connection, but the given image has some basic functionality broken as well:
```
$ docker run -it --rm alpine:3.13 ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: clock_gettime(MONOTONIC) failed

$ docker run -it --rm alpine:3.13 date
Sun Jan  0 00:100:4174038  1900

$ docker run -it --rm alpine:3.14 ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: clock_gettime(MONOTONIC) failed

$ docker run -it --rm alpine:3.14 date
Mon Jun  8 19:59:44 UTC 2071

$ docker run -it --rm alpine:latest ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: clock_gettime(MONOTONIC) failed

$ docker run -it --rm alpine:latest date
Thu Jun 11 10:34:24 UTC 2071
```

However, this works in 3.12:
```
$ docker run -it --rm alpine:3.12 ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=57 time=5.019 ms
...

$ docker run -it --rm alpine:3.12 date
Sat Jul 31 22:13:43 UTC 2021
```

I found a relevant issue [here](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12091) which is referring specifically to version 3.13.

**Comment by BohdanTkachenko** [comment]
Actually, this issue seems to go even deeper than this. I found this to be happening also for ubuntu:latest image. There is a [tracking bug](https://bugs.launchpad.net/cloud-images/+bug/1896443) for ubuntu for this. And it looks like the root cause is well described [here](https://askubuntu.com/a/1264921).

So instead of downgrading the image it is better to fix the issue on a host system.

**Comment by kpine** [comment]
Although I am not 100% opposed to downgrading to Alpine 3.12, the host solution is my preference. See also issue #1.

I would actually like to upgrade to Alpine 3.14, but node serialport does not compile for ARM platforms in my buildx configuration.

**Comment by BohdanTkachenko** [comment]
Thanks for the context! I could've save myself a lot of time if I checked closed issues in this project :)
